<?php

require "BerlinClock.php";
use PHPUnit\Framework\TestCase;

class BerlinClockTest extends TestCase
{
    private $berlinClock;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->berlinClock = new BerlinClock();
    }

    public function test_convert_given00Minutes_shouldReturn00Light(){
        $actual = $this->berlinClock->minutes();

        $this->assertEquals("00",$actual);
    }

    public function test_convert_given01Minutes_shouldReturn01Light(){
        $actual = $this->berlinClock->minutes();

        $this->assetEquals("01", $actual);
    }

    public function test_convert_given02Minutes_shouldReturn02Light(){
        $actual = $this->berlinClock->minutes();

        $this->assertEquals("02", $actual);
    }

    public function test_convert_given03Minutes_shouldReturn03Light(){
        $actual = $this->berlinClock->minutes();

        $this->assertEquals("03", $actual);
    }

    public function test_convert_given04Minutes_shouldReturn04Light(){
        $actual = $this->berlinClock->minutes();

        $this->assertEquals("04", $actual);
    }

}
